apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./cert-manager/controller/"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
  path: "./cert-manager/issuer/"
  validation: client
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
